const inventario = [
    {
        id: 0,
        name: 'Cemento Plástico Galón Bituplast',
        precio: 14,
        inv: 0,
    },
    {
        id: 1,
        name: "Cemento Plástico Cuñete (4 gln) Bituplast",
        precio: 38,
        inv: 0,
    },
    {
        id: 2,
        name: "Asfalto Líquido Cuñete (4 Gln) Bituplast",
        precio: 26,
        inv: 0,
    },
    {
        id: 3,
        name: "Asfalto Plástico 1/4 Galón Bituplast",
        precio: 7,
        inv: 0,
    },
    {
        id: 4,
        name: "Asfalto Plástico Galón Bituplast",
        precio: 10.5,
        inv: 0,
    },
    {
        id: 5,
        name: "Asfalto Plástico Cuñete (4 gln) Bituplast",
        precio: 30,
        inv: 0,
    },
    {
        id: 6,
        name: "Primer Galón Bituplast",
        precio: 13,
        inv: 0,
    },
    {
        id: 7,
        name: "Primer Cuñete (4 gln) Bituplast",
        precio: 27,
        inv: 0,
    },
    {
        id: 8,
        name: "Pintura Aluminizada Galón Bituplast",
        precio: 31,
        inv: 0,
    },
    {
        id: 9,
        name: "Pintura Aluminizada Cuñete (4 gln) Bituplast",
        precio: 105,
        inv: 0,
    },
    {
        id: 10,
        name: "Sellador de Capas Cuñete (4 gln) Bituplast",
        precio: 48,
        inv: 0,
    },
    {
        id: 11,
        name: "Manto BituAlum 3mm E.T. Rollo Bituplast",
        precio: 56,
        inv: 0,
    },
    {
        id: 12,
        name: "Manto Asfáltico 2.7mm Rollo Bituplast",
        precio: 27,
        inv: 0,
    },
    {
        id: 13,
        name: "Manto Asfáltico 3.2mm Rollo Bituplast",
        precio: 29,
        inv: 0,
    },
    {
        id: 14,
        name: "Bitubache Saco",
        precio: 25,
        inv: 0,
    },
    {
        id: 15,
        name: "Tanque Cilíndrico 500 Lt",
        precio: 90,
        inv: 0,
    },
    {
        id: 16,
        name: "Tanque Cilíndrico 560 Lt",
        precio: 95,
        inv: 0,
    },
    {
        id: 17,
        name: "Tanque Cilíndrico 1000 Lt",
        precio: 135,
        inv: 0,
    },
    {
        id: 18,
        name: "Tanque T/Vaso 1100 Lt",
        precio: 135,
        inv: 0,
    },
    {
        id: 19,
        name: "Tanque T/Vaso 2200 Lt",
        precio: 250,
        inv: 0,
    },
    {
        id: 20,
        name: "Tanque Tinaco 2000 Lt",
        precio: 290,
        inv: 0,
    },
    {
        id: 21,
        name: "Mapei Uno Garrafa 0.8 kg",
        precio: 5.5,
        inv: 0,
    },
    {
        id: 22,
        name: "Mapei Uno Garrafa 2 kg",
        precio: 13,
        inv: 0,
    },
    {
        id: 23,
        name: "Mapelatex CO Garrafa 0.8 kg",
        precio: 11.5,
        inv: 0,
    },
    {
        id: 24,
        name: "Mapelatex PVA Garrafa 0.25 kg",
        precio: 4,
        inv: 0,
    },
    {
        id: 25,
        name: "Mapelatex PVA Garrafa 1 kg",
        precio: 8.5,
        inv: 0,
    },
    {
        id: 26,
        name: "Mapeplast WP20 Garrafa 4.5 kg",
        precio: 26,
        inv: 0,
    },
    {
        id: 27,
        name: "MapeBand Easy H130 Rollo 10m",
        precio: 40,
        inv: 0,
    },
    {
        id: 28,
        name: "Aquaflex Techos Maxi Cuñete (5 gln) Blanco",
        precio: 135,
        inv: 0,
    },
    {
        id: 29,
        name: "Aquaflex Techos Maxi Cuñete (5 gln) Gris",
        precio: 135,
        inv: 0,
    },
    {
        id: 30,
        name: "Aquaflex Techos Maxi Cuñete (5 gln) Rojo",
        precio: 135,
        inv: 0,
    },
    {
        id: 31,
        name: "Aquaflex Techos Maxi Galón Blanco",
        precio: 35,
        inv: 0,
    },
    {
        id: 32,
        name: "Aquaflex Techos Maxi Galón Rojo",
        precio: 35,
        inv: 0,
    },
    {
        id: 33,
        name: "Mapeflex MS45 Crystal 300ml",
        precio: 18,
        inv: 0,
    },
    {
        id: 34,
        name: "Mapeflex MS45 Blanco 300ml",
        precio: 17,
        inv: 0,
    },
    {
        id: 35,
        name: "Mapeflex MS45 Gris 300ml",
        precio: 17,
        inv: 0,
    },
    {
        id: 36,
        name: "Mapeflex AC4 Blanco 300ml",
        precio: 7,
        inv: 0,
    },
    {
        id: 37,
        name: "Mapesil U Transparente 280ml",
        precio: 7,
        inv: 0,
    },
    {
        id: 38,
        name: "Ultrabond Super Grip 310ml",
        precio: 9,
        inv: 0,
    },
    {
        id: 39,
        name: "Mapepur Universal Foam 500ml",
        precio: 13,
        inv: 0,
    },
    {
        id: 40,
        name: "Mapepur Universal Foam 750ml",
        precio: 18,
        inv: 0,
    },
    {
        id: 41,
        name: "Eporip (A+B) Tarro 1.5kg + 0.5kg",
        precio: 100,
        inv: 0,
    },
    {
        id: 42,
        name: "Adesilex PG1 (A+B) Tarro 2kg",
        precio: 90,
        inv: 0,
    },
    {
        id: 43,
        name: "Keracolor FF 100 Blanco 2kg",
        precio: 6,
        inv: 0,
    },
    {
        id: 44,
        name: "Keracolor FF 113 Gris Cemento 2kg",
        precio: 6,
        inv: 0,
    },
    {
        id: 45,
        name: "Keracolor FF 142 Marrón 2kg",
        precio: 6,
        inv: 0,
    },
    {
        id: 46,
        name: "Keracolor FF 166 Fango 2kg",
        precio: 6,
        inv: 0,
    },
    {
        id: 47,
        name: "Keracolor FF 112 Gris Medio 5kg",
        precio: 11.5,
        inv: 0,
    },
    {
        id: 48,
        name: "Keracolor FF 142 Marrón 5kg",
        precio: 11.5,
        inv: 0,
    },
    {
        id: 49,
        name: "Keracolor FF 136 Barro Fango 5kg",
        precio: 11.5,
        inv: 0,
    },
];